print("Lets play Silly Senatances" )
name = input("Enter a Name:")
adjective = input("Enter an Adjective:")
adjective2 = input("Enter an Adjective:")
adverb = input("Enter an Adverb:")
food = input("Enter a Food:")
food2 = input("Enter a Food:")
noun = input("Enter a Noun:")
place = input("Enter a Place:")
verb = input("Enter a Verb:")
print(name + " was planning a dream vacation to " + place + "." ) 
print(name + " was especially looking forward to trying the local")
print("cuisine, including " + adjective + " " + food + " and " + food2 + ".\n")
print(name + " will have to practice the language " + adverb + " to")
print("make it easier to " + verb + " with people.\n\n")
print(name + " has a long list of sights to see, including the")
print(noun + " museum and the " + adjective2 +  " park.")

