name = input("Enter a Name:")
adjective = input("Enter an Adjective:")
adjective2 = input("Enter an Adjective:")
adverb = input("Enter an Adverb:")
food = input("Enter a Food:")
food2 = input("Enter a Food:")
noun = input("Enter a Noun:")
place = input("Enter a Place:")
verb = input("Enter a Verb:")
print(name + "was planning a dream vacation to" + place. + name + "was especially looking forward to trying the local cuisine, including" + adjective + food + "and" + food2 + "." + name + "will have to practice the language" + adverb + "to make it easier to " + verb + "with people."+ name + "has a long list of sights to see, including the" + noun + "museum and the " + adjective2 + "park.")